### ISSUE TITLE
[Feature request] Intellisense on shopify. translations

### ISSUE THREAD

**Issue by madsenmm** [Shopify/theme-tools#167]
When setting the `shopifyLiquid.themeCheckNextDevPreview: true`, would it be possible to enable intellisense on the `shopify.` translations?

i.e. 
```liquid
{{- 'shopify.checkout.shop_policies.shipping_policy' | t -}}
```

**_Currently kind of difficult to figure out the naming og those translation keys._**

**Comment by charlespwd** [comment]
Oh dear lol... TIL there are like 1500+ translations under the shopify.* namespace. But they aren't documented on shopify.dev. The list we use is outdated as it has ~800 items. 

On one hand, I'm not sure if we _want_ to surface those undocumented features as part of autocomplete. On the other, I understand how cumbersome it is to find the name of the key. 

How do you usually about finding the name of those keys anyway? You edit them in the theme content tab and then look at the changes to the locale file?

**Comment by tmmgrafikr** [comment]
Agree that it would be unstable to reference undocumented translation keys.

the easiest solution is to edit the translation, and look in the theme locale. Not sure there are other alternatives as of today.

previously you could inspect the DOM and find the key in there, but restructured and removed that.

probably a lot of them wouldn’t ever be used in the code.

the only ones I’ve ever had to use, were the sorting translations for search and collections, and the all the different policy translations

**Comment by charlespwd** [comment]
I mean, if we're being thorough we should probably figure out a way to have that updated automatically (like the docs are by being sent to [Shopify/theme-liquid-docs](/shopify/theme-liquid-docs)). Because the _check_ should never report an error on something that is kind of hidden and updated below our feet. 

For complete... Hmm... Might do it but "hidden" (e.g. they only appear if you try completing it after the entire shopify keyword has been typed rather than at the very beginning).
