### ISSUE TITLE
ICC hover documentation consistency

### ISSUE THREAD

**Issue by albchu** [Shopify/theme-tools#225]
**Describe the bug**
Formatting of the hover documentation for `shop.locale` is not like the rest of the hover documentation.

https://github.com/Shopify/theme-tools/assets/5607117/eb7df5c7-89a9-4046-b218-ea3b906150d6

**Expected behaviour**
Same hover doc structure everywhere.

**Additional context**
Its a deprecated field technically. Not sure if that makes a difference here.

**Comment by itsjustriley** [comment]
Upon investigation the missing 'Shopify reference' link appears to be the expected behaviour for deprecated tags. 

It's possible to change how we handle this by generating links to the docs for deprecated tags, and having them render on the hover for deprecated docs. However, once the docs for a deprecated tag are removed, we would lose consistency anyways (and we'd have to have handling for this as well). 

Given the investment required,  the challenge with consistency, and that these are deprecated tags, we're closing the issue.
