### ISSUE TITLE
'xxx.xxx.css' does not existtheme-check

### ISSUE THREAD

**Issue by MyBaymax** [Shopify/theme-tools#273]
**Describe the bug**

assets file name is `xxx.xxx.css`, filter `asset_url` does not resolve the path correctly

**Source**

```liquid
{{ 'yiling.snippet-product-form-countdown-code.css' | asset_url | stylesheet_tag }}
```

**Expected behaviour**

Correct Resolution Path

**Actual behaviour**

Error Massage
```
'assets/yiling.snippet-product-form-countdown-code.css' does not existtheme-check[MissingAsset](https://shopify.dev/docs/themes/tools/theme-check/checks/missing-asset)
```

**Debugging information**
 - OS Mac
 - OS Version 14.1.2 (23B92)
 - Theme Check Version 1.15.0
 - Shopify Liquid v2.0.0
 
**Additional context**

**Comment by charlespwd** [comment]
Does it or is this file built? I'm not sure what could go wrong? What's the output of `ls assets/`?

This check makes sure that there's a file named `yiling.snippet-product-form-countdown-code.css' in the `assets/` folder. 

I need more information about your setup because I don't think this is enough for me to reproduce

![image](https://github.com/Shopify/theme-tools/assets/4990691/66b70867-4999-4a4d-ba5d-06f91463329f)
