### ISSUE TITLE
Comma removed on new line generating Liquid syntax error

### ISSUE THREAD

**Issue by AssadRajab** [Shopify/theme-tools#481]
### The code
```
{%- liquid
  capture header_classes
    render 'responsive-classes',
    defaults : 'min-h-10 bg-gray-200',
    phone : 'flex flex-col p-2',
    tablet : 'flex flex-row p-2',
    desktop : 'flex flex-col p-4',
  endcapture
-%}
```

Simple: The comma after `render 'responsive-classes'` is being removed on formatting the document in vscode issuing a Liquid syntax error: `Liquid syntax error (line 4): Unknown tag 'defaults'`

**Comment by charlespwd** [comment]
This is invalid liquid. Try it out in the admin:
![Image](https://github.com/user-attachments/assets/d8756b71-dbee-4fc4-a5be-5c447330fd82)
![Image](https://github.com/user-attachments/assets/c2b6bd45-d633-4a2e-89cb-4bf8333e7934)

The `liquid` tag does not work multiline, it must be one line per statement. 

In the example above, since `default` appears on a new line, it expects it to be a new tag. 

You'd need to use full tags for this to work
```liquid
{% capture header_classes %}
  {% render 'responsive-classes',
    defaults : 'min-h-10 bg-gray-200',
    phone : 'flex flex-col p-2',
    tablet : 'flex flex-row p-2',
    desktop : 'flex flex-col p-4',
  %}
{% endcapture %}
```

That would work and would not cause prettier issues.

**Comment by AssadRajab** [comment]
Ah, I see. So either one line statment or to use full tags. Thank you.
