### ISSUE TITLE
Add a `required` attribute to input settings

### ISSUE THREAD

**Issue by stijns96** [Shopify/theme-tools#513]
**Is your feature request related to a problem? Please describe.**
I'm often running into the issue that I want to make settings required. Or at least let the client know that it is a required setting.

**Describe the solution you'd like**
Add a required attribute to schema input settings. It has to add a * next to the setting heading. Additionally it could also fire a warning in the editor if it's now filled in, but that's of course a bit more complex.

![Image](https://github.com/user-attachments/assets/7a793481-9f67-4775-933e-a502fdc2c33e)

**Checklist** 

- [ ] I have checked and made sure that the proposal adheres to this plugin's [principles](../../docs/prettier-plugin-liquid/principles/index.md)

**Additional context**

**Comment by charlespwd** [comment]
I unfortunately don't think we can do this because we'd need hooks that prevent against stale data (say a merchant deletes a collection after setting it in the theme editor). Things would get hairy really quickly. Plus you wouldn't be able to use the section on a freshly installed theme. 

The best thing you can do is a checking for `blank` in your liquid code. Perhaps show a placeholder / warning for merchants to fix their code when the setting isn't populated. 

> `blank`, if no selection has been made, the selection isn't visible, or the selection no longer exists.

https://shopify.dev/docs/storefronts/themes/architecture/settings/input-settings#collection

The feedback is noted, but since this isn't specifically a theme-tools issue (it is platform feedback), I will close this issue.
