### ISSUE TITLE
Support `content_for ""` first argument completion

### ISSUE THREAD

**Issue by charlespwd** [Shopify/theme-tools#569]
We want "block" or "blocks" completion in the LiquidString node.

```
{% content_for "█"%}
{% content_for "b█" %}
```

Steps:
- Create a `ContentForCompletionProvider` in theme-language-server-common/src/completions/providers
- Import it and add an instance to the list of providers in [theme-language-server-common/src/completions/CompletionProvider](https://github.com/smintfy/theme-tools/blob/main/packages/theme-language-server-common/src/completions/CompletionsProvider.ts#L1)
- Logic should be something like
  - Early return if the `node` from params.completionContext is not of type `NodeTypes.String` and the `parentNode` isn't a `ContentForMarkup` (check out the RenderSnippetCompletionProvider for inspiration)
  - Return completion items for `block` or `blocks`

**Comment by Smintfy** [comment]
Hello, @charlespwd

I added "block" and "blocks" completion inside the content_for tag. I hope the attached video is the desired feature or output. Hope you can check it out :)

I had to use the branch [feature/content_for_tag](https://github.com/Shopify/theme-tools/tree/feature/content_for_tag) to be able to use the `NodeTypes.ContentForMarkup` because I couldn't find it on the main branch 😅

https://github.com/user-attachments/assets/9f5aec3d-f6ed-467b-906e-c35f73856bc8

**Comment by charlespwd** [comment]
That's _exactly_ what we want :o

**Comment by charlespwd** [comment]
Fixed by #577 and #582
