### ISSUE TITLE
VS Shopify Liquid Extension > "Request textDocument/hover failed"

### ISSUE THREAD

**Issue by ceri-waterscreative** [Shopify/theme-tools#576]
While hovering of unsaved JSON files an error is produced: "Request textDocument/hover failed"
![Image](https://github.com/user-attachments/assets/92bb502e-7907-4085-8350-a62480345a84)

Latest verison of the CLI & Extension
Windows 11

See video here: 
https://streamable.com/6l9wqq

**Comment by charlespwd** [comment]
To whoever fixes this:

Looks like we're being too permissive in [here](https://github.com/Shopify/theme-tools/blob/main/packages/vscode-extension/src/browser/extension.ts#L43-L50) and [here](https://github.com/Shopify/theme-tools/blob/main/packages/vscode-extension/src/node/extension.ts#L54-L61) since we removed the `scheme` to give room for remote URIs. 

Given we check JSON files, we should make sure they are _theme_ JSON files before forwarding the requests to the JSON language service.
